version: '3'

services:
  back:
    build: .
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: back
    env_file: ./.env
    ports:
      - '7000:8000'
    volumes:
      - ./:/app
  
  bot:
    build: .
    restart: always
    command: bash -c "python manage.py bot"
    container_name: bot
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - back
