# Generated by Django 4.0 on 2023-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_sizes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcall',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
