# Generated by Django 4.0 on 2023-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_applicationcall_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonotification',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
